/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as ConviteTokenRouteImport } from './routes/convite.$token'
import { Route as Platform_adminProtectedRouteRouteImport } from './routes/platform_admin/_protected/route'
import { Route as Platform_adminLoginRouteImport } from './routes/platform_admin/login'
import { Route as Platform_adminProtectedIndexRouteImport } from './routes/platform_admin/_protected/index'
import { Route as Platform_adminProtectedUsersRouteImport } from './routes/platform_admin/_protected/users'
import { Route as Platform_adminConviteTokenRouteImport } from './routes/platform_admin/convite.$token'
import { Route as AuthenticatedAppOSlugRouteImport } from './routes/_authenticated/app.o.$slug'
import { Route as AuthenticatedAppOnboardingSlugRouteRouteImport } from './routes/_authenticated/app.onboarding.$slug/route'
import { Route as ApiPublicIngestTokenRouteImport } from './routes/api/public/ingest.$token'
import { Route as Platform_adminProtectedFlagsFlagsRouteImport } from './routes/platform_admin/_protected/_flags/flags'
import { Route as Platform_adminProtectedTiersTiersRouteImport } from './routes/platform_admin/_protected/_tiers/tiers'
import { Route as Platform_adminProtectedWebhooksWebhooksRouteImport } from './routes/platform_admin/_protected/_webhooks/webhooks'
import { Route as Platform_adminProtectedUsersIndexRouteImport } from './routes/platform_admin/_protected/users.index'
import { Route as Platform_adminProtectedUsersUserIdRouteImport } from './routes/platform_admin/_protected/users.$userId'
import { Route as AuthenticatedAppOSlugAlertasRouteImport } from './routes/_authenticated/app.o.$slug.alertas'
import { Route as AuthenticatedAppOSlugConfiguracoesRouteRouteImport } from './routes/_authenticated/app.o.$slug.configuracoes/route'
import { Route as AuthenticatedAppOSlugDashboardRouteImport } from './routes/_authenticated/app.o.$slug.dashboard'
import { Route as AuthenticatedAppOSlugEquipeRouteImport } from './routes/_authenticated/app.o.$slug.equipe'
import { Route as AuthenticatedAppOSlugFilaRouteRouteImport } from './routes/_authenticated/app.o.$slug.fila/route'
import { Route as Platform_adminProtectedFlagsFlagsIndexRouteImport } from './routes/platform_admin/_protected/_flags/flags.index'
import { Route as Platform_adminProtectedTiersTiersIndexRouteImport } from './routes/platform_admin/_protected/_tiers/tiers.index'
import { Route as Platform_adminProtectedWebhooksWebhooksIndexRouteImport } from './routes/platform_admin/_protected/_webhooks/webhooks.index'
import { Route as AuthenticatedAppOSlugFilaDemandasIdRouteRouteImport } from './routes/_authenticated/app.o.$slug.fila.demandas.$id/route'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ConviteTokenRoute = ConviteTokenRouteImport.update({
  id: '/convite/$token',
  path: '/convite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const Platform_adminProtectedRouteRoute =
  Platform_adminProtectedRouteRouteImport.update({
    id: '/platform_admin/_protected',
    path: '/platform_admin',
    getParentRoute: () => rootRouteImport,
  } as any)
const Platform_adminLoginRoute = Platform_adminLoginRouteImport.update({
  id: '/platform_admin/login',
  path: '/platform_admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const Platform_adminProtectedIndexRoute =
  Platform_adminProtectedIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Platform_adminProtectedRouteRoute,
  } as any)
const Platform_adminProtectedUsersRoute =
  Platform_adminProtectedUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => Platform_adminProtectedRouteRoute,
  } as any)
const Platform_adminConviteTokenRoute =
  Platform_adminConviteTokenRouteImport.update({
    id: '/platform_admin/convite/$token',
    path: '/platform_admin/convite/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppOSlugRoute = AuthenticatedAppOSlugRouteImport.update({
  id: '/o/$slug',
  path: '/o/$slug',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppOnboardingSlugRouteRoute =
  AuthenticatedAppOnboardingSlugRouteRouteImport.update({
    id: '/onboarding/$slug',
    path: '/onboarding/$slug',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const ApiPublicIngestTokenRoute = ApiPublicIngestTokenRouteImport.update({
  id: '/api/public/ingest/$token',
  path: '/api/public/ingest/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const Platform_adminProtectedFlagsFlagsRoute =
  Platform_adminProtectedFlagsFlagsRouteImport.update({
    id: '/_flags/flags',
    path: '/flags',
    getParentRoute: () => Platform_adminProtectedRouteRoute,
  } as any)
const Platform_adminProtectedTiersTiersRoute =
  Platform_adminProtectedTiersTiersRouteImport.update({
    id: '/_tiers/tiers',
    path: '/tiers',
    getParentRoute: () => Platform_adminProtectedRouteRoute,
  } as any)
const Platform_adminProtectedWebhooksWebhooksRoute =
  Platform_adminProtectedWebhooksWebhooksRouteImport.update({
    id: '/_webhooks/webhooks',
    path: '/webhooks',
    getParentRoute: () => Platform_adminProtectedRouteRoute,
  } as any)
const Platform_adminProtectedUsersIndexRoute =
  Platform_adminProtectedUsersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Platform_adminProtectedUsersRoute,
  } as any)
const Platform_adminProtectedUsersUserIdRoute =
  Platform_adminProtectedUsersUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => Platform_adminProtectedUsersRoute,
  } as any)
const AuthenticatedAppOSlugAlertasRoute =
  AuthenticatedAppOSlugAlertasRouteImport.update({
    id: '/alertas',
    path: '/alertas',
    getParentRoute: () => AuthenticatedAppOSlugRoute,
  } as any)
const AuthenticatedAppOSlugConfiguracoesRouteRoute =
  AuthenticatedAppOSlugConfiguracoesRouteRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAppOSlugRoute,
  } as any)
const AuthenticatedAppOSlugDashboardRoute =
  AuthenticatedAppOSlugDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAppOSlugRoute,
  } as any)
const AuthenticatedAppOSlugEquipeRoute =
  AuthenticatedAppOSlugEquipeRouteImport.update({
    id: '/equipe',
    path: '/equipe',
    getParentRoute: () => AuthenticatedAppOSlugRoute,
  } as any)
const AuthenticatedAppOSlugFilaRouteRoute =
  AuthenticatedAppOSlugFilaRouteRouteImport.update({
    id: '/fila',
    path: '/fila',
    getParentRoute: () => AuthenticatedAppOSlugRoute,
  } as any)
const Platform_adminProtectedFlagsFlagsIndexRoute =
  Platform_adminProtectedFlagsFlagsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Platform_adminProtectedFlagsFlagsRoute,
  } as any)
const Platform_adminProtectedTiersTiersIndexRoute =
  Platform_adminProtectedTiersTiersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Platform_adminProtectedTiersTiersRoute,
  } as any)
const Platform_adminProtectedWebhooksWebhooksIndexRoute =
  Platform_adminProtectedWebhooksWebhooksIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Platform_adminProtectedWebhooksWebhooksRoute,
  } as any)
const AuthenticatedAppOSlugFilaDemandasIdRouteRoute =
  AuthenticatedAppOSlugFilaDemandasIdRouteRouteImport.update({
    id: '/demandas/$id',
    path: '/demandas/$id',
    getParentRoute: () => AuthenticatedAppOSlugFilaRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/platform_admin': typeof Platform_adminProtectedRouteRouteWithChildren
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/convite/$token': typeof ConviteTokenRoute
  '/platform_admin/login': typeof Platform_adminLoginRoute
  '/platform_admin/users': typeof Platform_adminProtectedUsersRouteWithChildren
  '/platform_admin/convite/$token': typeof Platform_adminConviteTokenRoute
  '/platform_admin/': typeof Platform_adminProtectedIndexRoute
  '/app/onboarding/$slug': typeof AuthenticatedAppOnboardingSlugRouteRoute
  '/app/o/$slug': typeof AuthenticatedAppOSlugRouteWithChildren
  '/api/public/ingest/$token': typeof ApiPublicIngestTokenRoute
  '/platform_admin/flags': typeof Platform_adminProtectedFlagsFlagsRouteWithChildren
  '/platform_admin/tiers': typeof Platform_adminProtectedTiersTiersRouteWithChildren
  '/platform_admin/webhooks': typeof Platform_adminProtectedWebhooksWebhooksRouteWithChildren
  '/platform_admin/users/$userId': typeof Platform_adminProtectedUsersUserIdRoute
  '/platform_admin/users/': typeof Platform_adminProtectedUsersIndexRoute
  '/app/o/$slug/configuracoes': typeof AuthenticatedAppOSlugConfiguracoesRouteRoute
  '/app/o/$slug/fila': typeof AuthenticatedAppOSlugFilaRouteRouteWithChildren
  '/app/o/$slug/alertas': typeof AuthenticatedAppOSlugAlertasRoute
  '/app/o/$slug/dashboard': typeof AuthenticatedAppOSlugDashboardRoute
  '/app/o/$slug/equipe': typeof AuthenticatedAppOSlugEquipeRoute
  '/platform_admin/flags/': typeof Platform_adminProtectedFlagsFlagsIndexRoute
  '/platform_admin/tiers/': typeof Platform_adminProtectedTiersTiersIndexRoute
  '/platform_admin/webhooks/': typeof Platform_adminProtectedWebhooksWebhooksIndexRoute
  '/app/o/$slug/fila/demandas/$id': typeof AuthenticatedAppOSlugFilaDemandasIdRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/convite/$token': typeof ConviteTokenRoute
  '/platform_admin/login': typeof Platform_adminLoginRoute
  '/platform_admin/convite/$token': typeof Platform_adminConviteTokenRoute
  '/platform_admin': typeof Platform_adminProtectedIndexRoute
  '/app/onboarding/$slug': typeof AuthenticatedAppOnboardingSlugRouteRoute
  '/app/o/$slug': typeof AuthenticatedAppOSlugRouteWithChildren
  '/api/public/ingest/$token': typeof ApiPublicIngestTokenRoute
  '/platform_admin/users/$userId': typeof Platform_adminProtectedUsersUserIdRoute
  '/platform_admin/users': typeof Platform_adminProtectedUsersIndexRoute
  '/app/o/$slug/configuracoes': typeof AuthenticatedAppOSlugConfiguracoesRouteRoute
  '/app/o/$slug/fila': typeof AuthenticatedAppOSlugFilaRouteRouteWithChildren
  '/app/o/$slug/alertas': typeof AuthenticatedAppOSlugAlertasRoute
  '/app/o/$slug/dashboard': typeof AuthenticatedAppOSlugDashboardRoute
  '/app/o/$slug/equipe': typeof AuthenticatedAppOSlugEquipeRoute
  '/platform_admin/flags': typeof Platform_adminProtectedFlagsFlagsIndexRoute
  '/platform_admin/tiers': typeof Platform_adminProtectedTiersTiersIndexRoute
  '/platform_admin/webhooks': typeof Platform_adminProtectedWebhooksWebhooksIndexRoute
  '/app/o/$slug/fila/demandas/$id': typeof AuthenticatedAppOSlugFilaDemandasIdRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/platform_admin/_protected': typeof Platform_adminProtectedRouteRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/convite/$token': typeof ConviteTokenRoute
  '/platform_admin/login': typeof Platform_adminLoginRoute
  '/platform_admin/_protected/users': typeof Platform_adminProtectedUsersRouteWithChildren
  '/platform_admin/convite/$token': typeof Platform_adminConviteTokenRoute
  '/platform_admin/_protected/': typeof Platform_adminProtectedIndexRoute
  '/_authenticated/app/onboarding/$slug': typeof AuthenticatedAppOnboardingSlugRouteRoute
  '/_authenticated/app/o/$slug': typeof AuthenticatedAppOSlugRouteWithChildren
  '/api/public/ingest/$token': typeof ApiPublicIngestTokenRoute
  '/platform_admin/_protected/_flags/flags': typeof Platform_adminProtectedFlagsFlagsRouteWithChildren
  '/platform_admin/_protected/_tiers/tiers': typeof Platform_adminProtectedTiersTiersRouteWithChildren
  '/platform_admin/_protected/_webhooks/webhooks': typeof Platform_adminProtectedWebhooksWebhooksRouteWithChildren
  '/platform_admin/_protected/users/$userId': typeof Platform_adminProtectedUsersUserIdRoute
  '/platform_admin/_protected/users/': typeof Platform_adminProtectedUsersIndexRoute
  '/_authenticated/app/o/$slug/configuracoes': typeof AuthenticatedAppOSlugConfiguracoesRouteRoute
  '/_authenticated/app/o/$slug/fila': typeof AuthenticatedAppOSlugFilaRouteRouteWithChildren
  '/_authenticated/app/o/$slug/alertas': typeof AuthenticatedAppOSlugAlertasRoute
  '/_authenticated/app/o/$slug/dashboard': typeof AuthenticatedAppOSlugDashboardRoute
  '/_authenticated/app/o/$slug/equipe': typeof AuthenticatedAppOSlugEquipeRoute
  '/platform_admin/_protected/_flags/flags/': typeof Platform_adminProtectedFlagsFlagsIndexRoute
  '/platform_admin/_protected/_tiers/tiers/': typeof Platform_adminProtectedTiersTiersIndexRoute
  '/platform_admin/_protected/_webhooks/webhooks/': typeof Platform_adminProtectedWebhooksWebhooksIndexRoute
  '/_authenticated/app/o/$slug/fila/demandas/$id': typeof AuthenticatedAppOSlugFilaDemandasIdRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/platform_admin'
    | '/app'
    | '/convite/$token'
    | '/platform_admin/login'
    | '/platform_admin/users'
    | '/platform_admin/convite/$token'
    | '/platform_admin/'
    | '/app/onboarding/$slug'
    | '/app/o/$slug'
    | '/api/public/ingest/$token'
    | '/platform_admin/flags'
    | '/platform_admin/tiers'
    | '/platform_admin/webhooks'
    | '/platform_admin/users/$userId'
    | '/platform_admin/users/'
    | '/app/o/$slug/configuracoes'
    | '/app/o/$slug/fila'
    | '/app/o/$slug/alertas'
    | '/app/o/$slug/dashboard'
    | '/app/o/$slug/equipe'
    | '/platform_admin/flags/'
    | '/platform_admin/tiers/'
    | '/platform_admin/webhooks/'
    | '/app/o/$slug/fila/demandas/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app'
    | '/convite/$token'
    | '/platform_admin/login'
    | '/platform_admin/convite/$token'
    | '/platform_admin'
    | '/app/onboarding/$slug'
    | '/app/o/$slug'
    | '/api/public/ingest/$token'
    | '/platform_admin/users/$userId'
    | '/platform_admin/users'
    | '/app/o/$slug/configuracoes'
    | '/app/o/$slug/fila'
    | '/app/o/$slug/alertas'
    | '/app/o/$slug/dashboard'
    | '/app/o/$slug/equipe'
    | '/platform_admin/flags'
    | '/platform_admin/tiers'
    | '/platform_admin/webhooks'
    | '/app/o/$slug/fila/demandas/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/platform_admin/_protected'
    | '/_authenticated/app'
    | '/convite/$token'
    | '/platform_admin/login'
    | '/platform_admin/_protected/users'
    | '/platform_admin/convite/$token'
    | '/platform_admin/_protected/'
    | '/_authenticated/app/onboarding/$slug'
    | '/_authenticated/app/o/$slug'
    | '/api/public/ingest/$token'
    | '/platform_admin/_protected/_flags/flags'
    | '/platform_admin/_protected/_tiers/tiers'
    | '/platform_admin/_protected/_webhooks/webhooks'
    | '/platform_admin/_protected/users/$userId'
    | '/platform_admin/_protected/users/'
    | '/_authenticated/app/o/$slug/configuracoes'
    | '/_authenticated/app/o/$slug/fila'
    | '/_authenticated/app/o/$slug/alertas'
    | '/_authenticated/app/o/$slug/dashboard'
    | '/_authenticated/app/o/$slug/equipe'
    | '/platform_admin/_protected/_flags/flags/'
    | '/platform_admin/_protected/_tiers/tiers/'
    | '/platform_admin/_protected/_webhooks/webhooks/'
    | '/_authenticated/app/o/$slug/fila/demandas/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  Platform_adminProtectedRouteRoute: typeof Platform_adminProtectedRouteRouteWithChildren
  ConviteTokenRoute: typeof ConviteTokenRoute
  Platform_adminLoginRoute: typeof Platform_adminLoginRoute
  Platform_adminConviteTokenRoute: typeof Platform_adminConviteTokenRoute
  ApiPublicIngestTokenRoute: typeof ApiPublicIngestTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/convite/$token': {
      id: '/convite/$token'
      path: '/convite/$token'
      fullPath: '/convite/$token'
      preLoaderRoute: typeof ConviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform_admin/_protected': {
      id: '/platform_admin/_protected'
      path: '/platform_admin'
      fullPath: '/platform_admin'
      preLoaderRoute: typeof Platform_adminProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform_admin/login': {
      id: '/platform_admin/login'
      path: '/platform_admin/login'
      fullPath: '/platform_admin/login'
      preLoaderRoute: typeof Platform_adminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform_admin/_protected/': {
      id: '/platform_admin/_protected/'
      path: '/'
      fullPath: '/platform_admin/'
      preLoaderRoute: typeof Platform_adminProtectedIndexRouteImport
      parentRoute: typeof Platform_adminProtectedRouteRoute
    }
    '/platform_admin/_protected/users': {
      id: '/platform_admin/_protected/users'
      path: '/users'
      fullPath: '/platform_admin/users'
      preLoaderRoute: typeof Platform_adminProtectedUsersRouteImport
      parentRoute: typeof Platform_adminProtectedRouteRoute
    }
    '/platform_admin/convite/$token': {
      id: '/platform_admin/convite/$token'
      path: '/platform_admin/convite/$token'
      fullPath: '/platform_admin/convite/$token'
      preLoaderRoute: typeof Platform_adminConviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/o/$slug': {
      id: '/_authenticated/app/o/$slug'
      path: '/o/$slug'
      fullPath: '/app/o/$slug'
      preLoaderRoute: typeof AuthenticatedAppOSlugRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/onboarding/$slug': {
      id: '/_authenticated/app/onboarding/$slug'
      path: '/onboarding/$slug'
      fullPath: '/app/onboarding/$slug'
      preLoaderRoute: typeof AuthenticatedAppOnboardingSlugRouteRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/public/ingest/$token': {
      id: '/api/public/ingest/$token'
      path: '/api/public/ingest/$token'
      fullPath: '/api/public/ingest/$token'
      preLoaderRoute: typeof ApiPublicIngestTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform_admin/_protected/_flags/flags': {
      id: '/platform_admin/_protected/_flags/flags'
      path: '/flags'
      fullPath: '/platform_admin/flags'
      preLoaderRoute: typeof Platform_adminProtectedFlagsFlagsRouteImport
      parentRoute: typeof Platform_adminProtectedRouteRoute
    }
    '/platform_admin/_protected/_tiers/tiers': {
      id: '/platform_admin/_protected/_tiers/tiers'
      path: '/tiers'
      fullPath: '/platform_admin/tiers'
      preLoaderRoute: typeof Platform_adminProtectedTiersTiersRouteImport
      parentRoute: typeof Platform_adminProtectedRouteRoute
    }
    '/platform_admin/_protected/_webhooks/webhooks': {
      id: '/platform_admin/_protected/_webhooks/webhooks'
      path: '/webhooks'
      fullPath: '/platform_admin/webhooks'
      preLoaderRoute: typeof Platform_adminProtectedWebhooksWebhooksRouteImport
      parentRoute: typeof Platform_adminProtectedRouteRoute
    }
    '/platform_admin/_protected/users/': {
      id: '/platform_admin/_protected/users/'
      path: '/'
      fullPath: '/platform_admin/users/'
      preLoaderRoute: typeof Platform_adminProtectedUsersIndexRouteImport
      parentRoute: typeof Platform_adminProtectedUsersRoute
    }
    '/platform_admin/_protected/users/$userId': {
      id: '/platform_admin/_protected/users/$userId'
      path: '/$userId'
      fullPath: '/platform_admin/users/$userId'
      preLoaderRoute: typeof Platform_adminProtectedUsersUserIdRouteImport
      parentRoute: typeof Platform_adminProtectedUsersRoute
    }
    '/_authenticated/app/o/$slug/alertas': {
      id: '/_authenticated/app/o/$slug/alertas'
      path: '/alertas'
      fullPath: '/app/o/$slug/alertas'
      preLoaderRoute: typeof AuthenticatedAppOSlugAlertasRouteImport
      parentRoute: typeof AuthenticatedAppOSlugRoute
    }
    '/_authenticated/app/o/$slug/configuracoes': {
      id: '/_authenticated/app/o/$slug/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/o/$slug/configuracoes'
      preLoaderRoute: typeof AuthenticatedAppOSlugConfiguracoesRouteRouteImport
      parentRoute: typeof AuthenticatedAppOSlugRoute
    }
    '/_authenticated/app/o/$slug/dashboard': {
      id: '/_authenticated/app/o/$slug/dashboard'
      path: '/dashboard'
      fullPath: '/app/o/$slug/dashboard'
      preLoaderRoute: typeof AuthenticatedAppOSlugDashboardRouteImport
      parentRoute: typeof AuthenticatedAppOSlugRoute
    }
    '/_authenticated/app/o/$slug/equipe': {
      id: '/_authenticated/app/o/$slug/equipe'
      path: '/equipe'
      fullPath: '/app/o/$slug/equipe'
      preLoaderRoute: typeof AuthenticatedAppOSlugEquipeRouteImport
      parentRoute: typeof AuthenticatedAppOSlugRoute
    }
    '/_authenticated/app/o/$slug/fila': {
      id: '/_authenticated/app/o/$slug/fila'
      path: '/fila'
      fullPath: '/app/o/$slug/fila'
      preLoaderRoute: typeof AuthenticatedAppOSlugFilaRouteRouteImport
      parentRoute: typeof AuthenticatedAppOSlugRoute
    }
    '/platform_admin/_protected/_flags/flags/': {
      id: '/platform_admin/_protected/_flags/flags/'
      path: '/'
      fullPath: '/platform_admin/flags/'
      preLoaderRoute: typeof Platform_adminProtectedFlagsFlagsIndexRouteImport
      parentRoute: typeof Platform_adminProtectedFlagsFlagsRoute
    }
    '/platform_admin/_protected/_tiers/tiers/': {
      id: '/platform_admin/_protected/_tiers/tiers/'
      path: '/'
      fullPath: '/platform_admin/tiers/'
      preLoaderRoute: typeof Platform_adminProtectedTiersTiersIndexRouteImport
      parentRoute: typeof Platform_adminProtectedTiersTiersRoute
    }
    '/platform_admin/_protected/_webhooks/webhooks/': {
      id: '/platform_admin/_protected/_webhooks/webhooks/'
      path: '/'
      fullPath: '/platform_admin/webhooks/'
      preLoaderRoute: typeof Platform_adminProtectedWebhooksWebhooksIndexRouteImport
      parentRoute: typeof Platform_adminProtectedWebhooksWebhooksRoute
    }
    '/_authenticated/app/o/$slug/fila/demandas/$id': {
      id: '/_authenticated/app/o/$slug/fila/demandas/$id'
      path: '/demandas/$id'
      fullPath: '/app/o/$slug/fila/demandas/$id'
      preLoaderRoute: typeof AuthenticatedAppOSlugFilaDemandasIdRouteRouteImport
      parentRoute: typeof AuthenticatedAppOSlugFilaRouteRoute
    }
  }
}

interface AuthenticatedAppOSlugFilaRouteRouteChildren {
  AuthenticatedAppOSlugFilaDemandasIdRouteRoute: typeof AuthenticatedAppOSlugFilaDemandasIdRouteRoute
}

const AuthenticatedAppOSlugFilaRouteRouteChildren: AuthenticatedAppOSlugFilaRouteRouteChildren =
  {
    AuthenticatedAppOSlugFilaDemandasIdRouteRoute:
      AuthenticatedAppOSlugFilaDemandasIdRouteRoute,
  }

const AuthenticatedAppOSlugFilaRouteRouteWithChildren =
  AuthenticatedAppOSlugFilaRouteRoute._addFileChildren(
    AuthenticatedAppOSlugFilaRouteRouteChildren,
  )

interface AuthenticatedAppOSlugRouteChildren {
  AuthenticatedAppOSlugConfiguracoesRouteRoute: typeof AuthenticatedAppOSlugConfiguracoesRouteRoute
  AuthenticatedAppOSlugFilaRouteRoute: typeof AuthenticatedAppOSlugFilaRouteRouteWithChildren
  AuthenticatedAppOSlugAlertasRoute: typeof AuthenticatedAppOSlugAlertasRoute
  AuthenticatedAppOSlugDashboardRoute: typeof AuthenticatedAppOSlugDashboardRoute
  AuthenticatedAppOSlugEquipeRoute: typeof AuthenticatedAppOSlugEquipeRoute
}

const AuthenticatedAppOSlugRouteChildren: AuthenticatedAppOSlugRouteChildren = {
  AuthenticatedAppOSlugConfiguracoesRouteRoute:
    AuthenticatedAppOSlugConfiguracoesRouteRoute,
  AuthenticatedAppOSlugFilaRouteRoute:
    AuthenticatedAppOSlugFilaRouteRouteWithChildren,
  AuthenticatedAppOSlugAlertasRoute: AuthenticatedAppOSlugAlertasRoute,
  AuthenticatedAppOSlugDashboardRoute: AuthenticatedAppOSlugDashboardRoute,
  AuthenticatedAppOSlugEquipeRoute: AuthenticatedAppOSlugEquipeRoute,
}

const AuthenticatedAppOSlugRouteWithChildren =
  AuthenticatedAppOSlugRoute._addFileChildren(
    AuthenticatedAppOSlugRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppOnboardingSlugRouteRoute: typeof AuthenticatedAppOnboardingSlugRouteRoute
  AuthenticatedAppOSlugRoute: typeof AuthenticatedAppOSlugRouteWithChildren
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppOnboardingSlugRouteRoute:
    AuthenticatedAppOnboardingSlugRouteRoute,
  AuthenticatedAppOSlugRoute: AuthenticatedAppOSlugRouteWithChildren,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface Platform_adminProtectedUsersRouteChildren {
  Platform_adminProtectedUsersUserIdRoute: typeof Platform_adminProtectedUsersUserIdRoute
  Platform_adminProtectedUsersIndexRoute: typeof Platform_adminProtectedUsersIndexRoute
}

const Platform_adminProtectedUsersRouteChildren: Platform_adminProtectedUsersRouteChildren =
  {
    Platform_adminProtectedUsersUserIdRoute:
      Platform_adminProtectedUsersUserIdRoute,
    Platform_adminProtectedUsersIndexRoute:
      Platform_adminProtectedUsersIndexRoute,
  }

const Platform_adminProtectedUsersRouteWithChildren =
  Platform_adminProtectedUsersRoute._addFileChildren(
    Platform_adminProtectedUsersRouteChildren,
  )

interface Platform_adminProtectedFlagsFlagsRouteChildren {
  Platform_adminProtectedFlagsFlagsIndexRoute: typeof Platform_adminProtectedFlagsFlagsIndexRoute
}

const Platform_adminProtectedFlagsFlagsRouteChildren: Platform_adminProtectedFlagsFlagsRouteChildren =
  {
    Platform_adminProtectedFlagsFlagsIndexRoute:
      Platform_adminProtectedFlagsFlagsIndexRoute,
  }

const Platform_adminProtectedFlagsFlagsRouteWithChildren =
  Platform_adminProtectedFlagsFlagsRoute._addFileChildren(
    Platform_adminProtectedFlagsFlagsRouteChildren,
  )

interface Platform_adminProtectedTiersTiersRouteChildren {
  Platform_adminProtectedTiersTiersIndexRoute: typeof Platform_adminProtectedTiersTiersIndexRoute
}

const Platform_adminProtectedTiersTiersRouteChildren: Platform_adminProtectedTiersTiersRouteChildren =
  {
    Platform_adminProtectedTiersTiersIndexRoute:
      Platform_adminProtectedTiersTiersIndexRoute,
  }

const Platform_adminProtectedTiersTiersRouteWithChildren =
  Platform_adminProtectedTiersTiersRoute._addFileChildren(
    Platform_adminProtectedTiersTiersRouteChildren,
  )

interface Platform_adminProtectedWebhooksWebhooksRouteChildren {
  Platform_adminProtectedWebhooksWebhooksIndexRoute: typeof Platform_adminProtectedWebhooksWebhooksIndexRoute
}

const Platform_adminProtectedWebhooksWebhooksRouteChildren: Platform_adminProtectedWebhooksWebhooksRouteChildren =
  {
    Platform_adminProtectedWebhooksWebhooksIndexRoute:
      Platform_adminProtectedWebhooksWebhooksIndexRoute,
  }

const Platform_adminProtectedWebhooksWebhooksRouteWithChildren =
  Platform_adminProtectedWebhooksWebhooksRoute._addFileChildren(
    Platform_adminProtectedWebhooksWebhooksRouteChildren,
  )

interface Platform_adminProtectedRouteRouteChildren {
  Platform_adminProtectedUsersRoute: typeof Platform_adminProtectedUsersRouteWithChildren
  Platform_adminProtectedIndexRoute: typeof Platform_adminProtectedIndexRoute
  Platform_adminProtectedFlagsFlagsRoute: typeof Platform_adminProtectedFlagsFlagsRouteWithChildren
  Platform_adminProtectedTiersTiersRoute: typeof Platform_adminProtectedTiersTiersRouteWithChildren
  Platform_adminProtectedWebhooksWebhooksRoute: typeof Platform_adminProtectedWebhooksWebhooksRouteWithChildren
}

const Platform_adminProtectedRouteRouteChildren: Platform_adminProtectedRouteRouteChildren =
  {
    Platform_adminProtectedUsersRoute:
      Platform_adminProtectedUsersRouteWithChildren,
    Platform_adminProtectedIndexRoute: Platform_adminProtectedIndexRoute,
    Platform_adminProtectedFlagsFlagsRoute:
      Platform_adminProtectedFlagsFlagsRouteWithChildren,
    Platform_adminProtectedTiersTiersRoute:
      Platform_adminProtectedTiersTiersRouteWithChildren,
    Platform_adminProtectedWebhooksWebhooksRoute:
      Platform_adminProtectedWebhooksWebhooksRouteWithChildren,
  }

const Platform_adminProtectedRouteRouteWithChildren =
  Platform_adminProtectedRouteRoute._addFileChildren(
    Platform_adminProtectedRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  Platform_adminProtectedRouteRoute:
    Platform_adminProtectedRouteRouteWithChildren,
  ConviteTokenRoute: ConviteTokenRoute,
  Platform_adminLoginRoute: Platform_adminLoginRoute,
  Platform_adminConviteTokenRoute: Platform_adminConviteTokenRoute,
  ApiPublicIngestTokenRoute: ApiPublicIngestTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
