/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicIngestTokenRouteImport } from './routes/api/public/ingest.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestTokenRoute = ApiPublicIngestTokenRouteImport.update({
  id: '/api/public/ingest/$token',
  path: '/api/public/ingest/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/ingest/$token': typeof ApiPublicIngestTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/ingest/$token': typeof ApiPublicIngestTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/ingest/$token': typeof ApiPublicIngestTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/ingest/$token'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/ingest/$token'
  id: '__root__' | '/' | '/api/public/ingest/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicIngestTokenRoute: typeof ApiPublicIngestTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest/$token': {
      id: '/api/public/ingest/$token'
      path: '/api/public/ingest/$token'
      fullPath: '/api/public/ingest/$token'
      preLoaderRoute: typeof ApiPublicIngestTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicIngestTokenRoute: ApiPublicIngestTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
